# Generated by Django 2.2.16 on 2022-01-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211208_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', '-pk']},
        ),
    ]
